# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastro2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 807)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    color: #000;\n"
"    border: none;\n"
"    \n"
"    font: 16pt \"MS Shell Dlg 2\";\n"
"}\n"
"#centralwidget{\n"
"    background-color: #eff9fe;\n"
"\n"
"}\n"
" #frame_11{\n"
"    background-color: #2596be;\n"
"}\n"
"QLineEdit{\n"
"    border-color: black;\n"
"    color: #2596be;\n"
"}\n"
"#searchFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid #2596be;\n"
"}\n"
"#appHeader{\n"
"    color: #2596be;\n"
"}\n"
"#card1, #card2, #card3, #card4 {\n"
"    background-color: #fefeff;\n"
"    border-radius: 20px;\n"
"}\n"
"#btnCancelar, #btnCadastrar, #btnReset{\n"
"    background-color: #2596be;\n"
"    color: #fff;\n"
"    border-radius: 10px;\n"
"}\n"
"#widget_4, #widget_5, #profileCont, #frame_15{\n"
"    background-color: #fefeff;\n"
"    border-radius: 20px;\n"
"}\n"
"#headerFrame{\n"
"    background-color: #fefeff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 10px 5px;\n"
"    text-align: center;\n"
"}\n"
"#centralwidget{\n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"#line{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.btnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCadastrar.setGeometry(QtCore.QRect(120, 610, 151, 51))
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setGeometry(QtCore.QRect(30, 690, 131, 51))
        self.btnReset.setObjectName("btnReset")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 60, 71, 31))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 130, 161, 41))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 320, 151, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(150, 400, 61, 41))
        self.label_7.setObjectName("label_7")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 15, 171, 31))
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.inpuNome = QtWidgets.QLineEdit(self.centralwidget)
        self.inpuNome.setGeometry(QtCore.QRect(20, 100, 341, 31))
        self.inpuNome.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.inpuNome.setObjectName("inpuNome")
        self.inputPet = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPet.setGeometry(QtCore.QRect(20, 180, 341, 31))
        self.inputPet.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.inputPet.setObjectName("inputPet")
        self.inputWats = QtWidgets.QLineEdit(self.centralwidget)
        self.inputWats.setGeometry(QtCore.QRect(20, 360, 341, 31))
        self.inputWats.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.inputWats.setObjectName("inputWats")
        self.inputEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.inputEmail.setGeometry(QtCore.QRect(20, 450, 341, 31))
        self.inputEmail.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.inputEmail.setObjectName("inputEmail")
        self.btnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancelar.setGeometry(QtCore.QRect(240, 690, 131, 51))
        self.btnCancelar.setObjectName("btnCancelar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCadastrar.setText(_translate("MainWindow", "Cadastar"))
        self.btnReset.setText(_translate("MainWindow", "resetar"))
        self.label.setText(_translate("MainWindow", "Nome:"))
        self.label_4.setText(_translate("MainWindow", "Especie do PET:"))
        self.label_6.setText(_translate("MainWindow", "Telefone/Watss:"))
        self.label_7.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Tela de cadastro"))
        self.btnCancelar.setText(_translate("MainWindow", "cancelar"))
