# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroDespesa.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1370, 898)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(30, 10, 1041, 681))
        self.widget.setMinimumSize(QtCore.QSize(1041, 681))
        self.widget.setMaximumSize(QtCore.QSize(1041, 681))
        self.widget.setStyleSheet("\n"
"background-color: rgba(86,109,124,255);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(20, 50, 971, 541))
        self.widget_2.setMinimumSize(QtCore.QSize(971, 541))
        self.widget_2.setMaximumSize(QtCore.QSize(971, 541))
        self.widget_2.setStyleSheet("background-color: rgba(207,222,229,255);")
        self.widget_2.setObjectName("widget_2")
        self.frame_6 = QtWidgets.QFrame(self.widget_2)
        self.frame_6.setGeometry(QtCore.QRect(50, 110, 811, 111))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.inputDespesa = QtWidgets.QLineEdit(self.frame_6)
        self.inputDespesa.setGeometry(QtCore.QRect(210, 40, 201, 31))
        self.inputDespesa.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);")
        self.inputDespesa.setObjectName("inputDespesa")
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(230, 10, 101, 21))
        self.label_16.setStyleSheet("color: #000;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(40, 0, 61, 41))
        self.label_17.setStyleSheet("color: #000;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_17.setObjectName("label_17")
        self.cb_tipo = QtWidgets.QComboBox(self.frame_6)
        self.cb_tipo.setGeometry(QtCore.QRect(40, 40, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_tipo.sizePolicy().hasHeightForWidth())
        self.cb_tipo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cb_tipo.setFont(font)
        self.cb_tipo.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"color: rgb(0, 0, 0);")
        self.cb_tipo.setObjectName("cb_tipo")
        self.cb_tipo.addItem("")
        self.cb_tipo.addItem("")
        self.cb_status = QtWidgets.QComboBox(self.frame_6)
        self.cb_status.setGeometry(QtCore.QRect(510, 40, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_status.sizePolicy().hasHeightForWidth())
        self.cb_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cb_status.setFont(font)
        self.cb_status.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"color: rgb(0, 0, 0);")
        self.cb_status.setObjectName("cb_status")
        self.cb_status.addItem("")
        self.cb_status.addItem("")
        self.label_19 = QtWidgets.QLabel(self.frame_6)
        self.label_19.setGeometry(QtCore.QRect(510, 0, 61, 31))
        self.label_19.setStyleSheet("color: #000;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_19.setObjectName("label_19")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(50, 40, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #000;\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_2)
        self.radioButton_2.setGeometry(QtCore.QRect(620, 410, 51, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.frame_7 = QtWidgets.QFrame(self.widget_2)
        self.frame_7.setGeometry(QtCore.QRect(50, 220, 811, 111))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_26 = QtWidgets.QLabel(self.frame_7)
        self.label_26.setGeometry(QtCore.QRect(190, 10, 81, 41))
        self.label_26.setStyleSheet("color: #000;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.cb_agendado = QtWidgets.QComboBox(self.frame_7)
        self.cb_agendado.setGeometry(QtCore.QRect(190, 50, 151, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_agendado.sizePolicy().hasHeightForWidth())
        self.cb_agendado.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cb_agendado.setFont(font)
        self.cb_agendado.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"color: rgb(0, 0, 0);")
        self.cb_agendado.setObjectName("cb_agendado")
        self.cb_agendado.addItem("")
        self.cb_agendado.addItem("")
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(40, 20, 101, 21))
        self.label_18.setStyleSheet("color: #000;\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.label_18.setObjectName("label_18")
        self.inputTotal = QtWidgets.QLineEdit(self.frame_7)
        self.inputTotal.setGeometry(QtCore.QRect(20, 50, 141, 31))
        self.inputTotal.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);")
        self.inputTotal.setObjectName("inputTotal")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(390, 50, 371, 21))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.inpuDia = QtWidgets.QLineEdit(self.frame_8)
        self.inpuDia.setGeometry(QtCore.QRect(40, 0, 71, 21))
        self.inpuDia.setStyleSheet("border-style: outset;\n"
"border-width:2px;\n"
"color: rgb(0, 0, 0);")
        self.inpuDia.setObjectName("inpuDia")
        self.inpuMes = QtWidgets.QLineEdit(self.frame_8)
        self.inpuMes.setGeometry(QtCore.QRect(170, 0, 71, 21))
        self.inpuMes.setStyleSheet("border-style: outset;\n"
"border-width:2px;\n"
"color: rgb(0, 0, 0);")
        self.inpuMes.setObjectName("inpuMes")
        self.inpuAno = QtWidgets.QLineEdit(self.frame_8)
        self.inpuAno.setGeometry(QtCore.QRect(280, 0, 71, 21))
        self.inpuAno.setStyleSheet("border-style: outset;\n"
"border-width:2px;\n"
"color: rgb(0, 0, 0);")
        self.inpuAno.setObjectName("inpuAno")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setGeometry(QtCore.QRect(310, 30, 421, 16))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(120, -10, 61, 41))
        self.label_20.setStyleSheet("color: #000;")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(260, -10, 41, 41))
        self.label_21.setStyleSheet("color: #000;")
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.frame_9)
        self.label_24.setGeometry(QtCore.QRect(360, 0, 41, 21))
        self.label_24.setStyleSheet("color: #000;")
        self.label_24.setObjectName("label_24")
        self.frame_12 = QtWidgets.QFrame(self.widget_2)
        self.frame_12.setGeometry(QtCore.QRect(-20, 330, 1041, 111))
        self.frame_12.setStyleSheet("\n"
"background-color: rgba(86,109,124,255);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame = QtWidgets.QFrame(self.frame_12)
        self.frame.setGeometry(QtCore.QRect(60, 20, 811, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnReset = QtWidgets.QPushButton(self.frame)
        self.btnReset.setGeometry(QtCore.QRect(50, 0, 131, 51))
        self.btnReset.setStyleSheet("border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: rgb(85, 170, 255);\n"
"color: #000;")
        self.btnReset.setObjectName("btnReset")
        self.btnCadastrar = QtWidgets.QPushButton(self.frame)
        self.btnCadastrar.setGeometry(QtCore.QRect(340, 0, 151, 51))
        self.btnCadastrar.setStyleSheet("border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"color: #000;\n"
"background-color: rgb(85, 255, 127);")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnCancelar = QtWidgets.QPushButton(self.frame)
        self.btnCancelar.setGeometry(QtCore.QRect(620, 0, 131, 51))
        self.btnCancelar.setStyleSheet("border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: red;\n"
"color: #000;")
        self.btnCancelar.setObjectName("btnCancelar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1370, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_16.setText(_translate("MainWindow", "Despesa:"))
        self.label_17.setText(_translate("MainWindow", "Tipo:"))
        self.cb_tipo.setItemText(0, _translate("MainWindow", "Banho"))
        self.cb_tipo.setItemText(1, _translate("MainWindow", "Tosa"))
        self.cb_status.setItemText(0, _translate("MainWindow", "Pendente"))
        self.cb_status.setItemText(1, _translate("MainWindow", "New Item"))
        self.label_19.setText(_translate("MainWindow", "Status:"))
        self.label_5.setText(_translate("MainWindow", "Inserir despesa"))
        self.radioButton_2.setText(_translate("MainWindow", "Não"))
        self.label_26.setText(_translate("MainWindow", "Agendado:"))
        self.cb_agendado.setItemText(0, _translate("MainWindow", "Não"))
        self.cb_agendado.setItemText(1, _translate("MainWindow", "Sim"))
        self.label_18.setText(_translate("MainWindow", "Valor:"))
        self.label_20.setText(_translate("MainWindow", "Dia:"))
        self.label_21.setText(_translate("MainWindow", "Mes:"))
        self.label_24.setText(_translate("MainWindow", "Ano:"))
        self.btnReset.setText(_translate("MainWindow", "resetar"))
        self.btnCadastrar.setText(_translate("MainWindow", "Salvar"))
        self.btnCancelar.setText(_translate("MainWindow", "cancelar"))
