# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cadastroCliente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1038, 676)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    color: #000;\n"
"    border: none;\n"
"    \n"
"    font: 13pt \"MS Shell Dlg 2\";\n"
"}\n"
"#centralwidget{\n"
"    background-color: #eff9fe;\n"
"\n"
"}\n"
" #frame_11{\n"
"    background-color: #2596be;\n"
"}\n"
"QLineEdit{\n"
"    border-color: black;\n"
"    color: #2596be;\n"
"}\n"
"#searchFrame{\n"
"    border-radius: 10px;\n"
"    border: 2px solid #2596be;\n"
"}\n"
"#appHeader{\n"
"    color: #2596be;\n"
"}\n"
"#card1, #card2, #card3, #card4 {\n"
"    background-color: #fefeff;\n"
"    border-radius: 20px;\n"
"}\n"
"#btnCancelar, #btnCadastrar, #btnReset{\n"
"    background-color: #2596be;\n"
"    border-radius: 10px;\n"
"}\n"
"#widget_4, #widget_5, #profileCont, #frame_15{\n"
"    background-color: #fefeff;\n"
"    border-radius: 20px;\n"
"}\n"
"#headerFrame{\n"
"    background-color: #fefeff;\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding: 10px 5px;\n"
"    text-align: center;\n"
"}\n"
"#centralwidget{\n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"}\n"
"#line{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1041, 681))
        self.widget.setStyleSheet("color: rgb(85, 255, 0);\n"
"background-color: rgba(86,109,124,255);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(20, 50, 971, 541))
        self.widget_2.setMinimumSize(QtCore.QSize(971, 541))
        self.widget_2.setMaximumSize(QtCore.QSize(971, 541))
        self.widget_2.setStyleSheet("background-color: rgba(207,222,229,255);")
        self.widget_2.setObjectName("widget_2")
        self.label_9 = QtWidgets.QLabel(self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(120, 260, 151, 41))
        self.label_9.setStyleSheet("color: #000;")
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(510, 90, 101, 31))
        self.label_3.setStyleSheet("color: #000;")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(510, 170, 161, 41))
        self.label_5.setStyleSheet("color: #000;")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(120, 90, 71, 31))
        self.label_2.setStyleSheet("color: #000;")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(120, 170, 161, 41))
        self.label_4.setStyleSheet("color: #000;")
        self.label_4.setObjectName("label_4")
        self.inpuNome = QtWidgets.QLineEdit(self.widget_2)
        self.inpuNome.setGeometry(QtCore.QRect(120, 130, 341, 31))
        self.inpuNome.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inpuNome.setObjectName("inpuNome")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(370, 30, 221, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #000;\n"
"font: 22pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.inputWats = QtWidgets.QLineEdit(self.widget_2)
        self.inputWats.setGeometry(QtCore.QRect(120, 300, 341, 31))
        self.inputWats.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inputWats.setObjectName("inputWats")
        self.inpuCpf = QtWidgets.QLineEdit(self.widget_2)
        self.inpuCpf.setGeometry(QtCore.QRect(120, 210, 341, 31))
        self.inpuCpf.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inpuCpf.setObjectName("inpuCpf")
        self.inputPet = QtWidgets.QLineEdit(self.widget_2)
        self.inputPet.setGeometry(QtCore.QRect(510, 210, 341, 31))
        self.inputPet.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inputPet.setObjectName("inputPet")
        self.inputEmail = QtWidgets.QLineEdit(self.widget_2)
        self.inputEmail.setGeometry(QtCore.QRect(510, 300, 341, 31))
        self.inputEmail.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inputEmail.setObjectName("inputEmail")
        self.inpuSobrenome = QtWidgets.QLineEdit(self.widget_2)
        self.inpuSobrenome.setGeometry(QtCore.QRect(510, 130, 341, 31))
        self.inpuSobrenome.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inpuSobrenome.setObjectName("inpuSobrenome")
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setGeometry(QtCore.QRect(140, 350, 811, 71))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.inputNumero = QtWidgets.QLineEdit(self.frame_2)
        self.inputNumero.setGeometry(QtCore.QRect(560, 40, 101, 31))
        self.inputNumero.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inputNumero.setObjectName("inputNumero")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(190, 0, 81, 41))
        self.label_8.setStyleSheet("color: #000;")
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(60, 0, 61, 41))
        self.label_7.setStyleSheet("color: #000;")
        self.label_7.setObjectName("label_7")
        self.cb_uf = QtWidgets.QComboBox(self.frame_2)
        self.cb_uf.setGeometry(QtCore.QRect(40, 40, 101, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cb_uf.sizePolicy().hasHeightForWidth())
        self.cb_uf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.cb_uf.setFont(font)
        self.cb_uf.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.cb_uf.setObjectName("cb_uf")
        self.cb_uf.addItem("")
        self.cb_uf.addItem("")
        self.inpuEndereco = QtWidgets.QLineEdit(self.frame_2)
        self.inpuEndereco.setGeometry(QtCore.QRect(180, 40, 341, 31))
        self.inpuEndereco.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"")
        self.inpuEndereco.setObjectName("inpuEndereco")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(570, 10, 81, 21))
        self.label_10.setStyleSheet("color: #000;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.widget_2)
        self.label_11.setGeometry(QtCore.QRect(520, 270, 151, 21))
        self.label_11.setStyleSheet("color: #000;")
        self.label_11.setObjectName("label_11")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(120, 610, 811, 51))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btnReset = QtWidgets.QPushButton(self.frame)
        self.btnReset.setGeometry(QtCore.QRect(50, 0, 131, 51))
        self.btnReset.setStyleSheet("border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: rgb(85, 170, 255);\n"
"color: #000;")
        self.btnReset.setObjectName("btnReset")
        self.btnCadastrar = QtWidgets.QPushButton(self.frame)
        self.btnCadastrar.setGeometry(QtCore.QRect(340, 0, 151, 51))
        self.btnCadastrar.setStyleSheet("border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"color: #000;\n"
"background-color: rgb(85, 255, 127);")
        self.btnCadastrar.setObjectName("btnCadastrar")
        self.btnCancelar = QtWidgets.QPushButton(self.frame)
        self.btnCancelar.setGeometry(QtCore.QRect(620, 0, 131, 51))
        self.btnCancelar.setStyleSheet("border-radius: 15px;\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;\n"
"background-color: red;\n"
"color: #000;")
        self.btnCancelar.setObjectName("btnCancelar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Telefone/Watss:"))
        self.label_3.setText(_translate("MainWindow", "Sobrenome:"))
        self.label_5.setText(_translate("MainWindow", "Pet:"))
        self.label_2.setText(_translate("MainWindow", "Nome:"))
        self.label_4.setText(_translate("MainWindow", "CPF:"))
        self.label.setText(_translate("MainWindow", "Tela de Cadastro"))
        self.label_8.setText(_translate("MainWindow", "Endereço:"))
        self.label_7.setText(_translate("MainWindow", "UF:"))
        self.cb_uf.setItemText(0, _translate("MainWindow", "Usuário"))
        self.cb_uf.setItemText(1, _translate("MainWindow", "Administrador"))
        self.label_10.setText(_translate("MainWindow", "Numero:"))
        self.label_11.setText(_translate("MainWindow", "Email"))
        self.btnReset.setText(_translate("MainWindow", "resetar"))
        self.btnCadastrar.setText(_translate("MainWindow", "Cadastar"))
        self.btnCancelar.setText(_translate("MainWindow", "cancelar"))
