# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1642, 969)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1451, 901))
        self.frame.setStyleSheet("\n"
"background-color: rgba(86,109,124,255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setGeometry(QtCore.QRect(60, 50, 1341, 801))
        self.tabWidget.setStyleSheet("font: 19pt \"MS Sans Serif\";\n"
"background-color: rgba(207,222,229,255);\n"
"border-radius: 1px;\n"
"border-width:2px;")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.label_8 = QtWidgets.QLabel(self.tab_13)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 1341, 761))
        self.label_8.setStyleSheet("background-color: #3498db;\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_13, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(730, 50, 611, 221))
        self.tableWidget.setStyleSheet("QTableView {\n"
"    background-color: #3498db;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(-10, 0, 1351, 51))
        self.label_18.setStyleSheet("background-color: #3498db;\n"
"")
        self.label_18.setObjectName("label_18")
        self.btnPesquisar_2 = QtWidgets.QPushButton(self.tab_2)
        self.btnPesquisar_2.setGeometry(QtCore.QRect(730, 270, 161, 51))
        self.btnPesquisar_2.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnPesquisar_2.setObjectName("btnPesquisar_2")
        self.btnAtualizar_3 = QtWidgets.QPushButton(self.tab_2)
        self.btnAtualizar_3.setGeometry(QtCore.QRect(900, 270, 161, 51))
        self.btnAtualizar_3.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnAtualizar_3.setObjectName("btnAtualizar_3")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(60, 100, 511, 431))
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border: 2px solid #000000;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setStyleSheet("QLabel{\n"
"\n"
"border: none;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.grafica_um = QtWidgets.QVBoxLayout()
        self.grafica_um.setObjectName("grafica_um")
        self.verticalLayout_6.addLayout(self.grafica_um)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 5)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 591, 31))
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.tabelaClientes = QtWidgets.QTableWidget(self.tab_10)
        self.tabelaClientes.setGeometry(QtCore.QRect(0, 20, 1331, 521))
        self.tabelaClientes.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabelaClientes.setStyleSheet("QTableView {\n"
"    background-color: #3498db;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}")
        self.tabelaClientes.setObjectName("tabelaClientes")
        self.tabelaClientes.setColumnCount(10)
        self.tabelaClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tabelaClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaClientes.setHorizontalHeaderItem(9, item)
        self.tabelaClientes.horizontalHeader().setDefaultSectionSize(140)
        self.tabelaClientes.horizontalHeader().setStretchLastSection(True)
        self.tabelaClientes.verticalHeader().setDefaultSectionSize(30)
        self.frame_6 = QtWidgets.QFrame(self.tab_10)
        self.frame_6.setGeometry(QtCore.QRect(40, 690, 1211, 66))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnDeleteClientes = QtWidgets.QPushButton(self.frame_6)
        self.btnDeleteClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnDeleteClientes.setObjectName("btnDeleteClientes")
        self.horizontalLayout_5.addWidget(self.btnDeleteClientes)
        self.btnGerarExelClientes = QtWidgets.QPushButton(self.frame_6)
        self.btnGerarExelClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnGerarExelClientes.setObjectName("btnGerarExelClientes")
        self.horizontalLayout_5.addWidget(self.btnGerarExelClientes)
        self.btnInserirClientes = QtWidgets.QPushButton(self.frame_6)
        self.btnInserirClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnInserirClientes.setObjectName("btnInserirClientes")
        self.horizontalLayout_5.addWidget(self.btnInserirClientes)
        self.btnLimparClientes = QtWidgets.QPushButton(self.frame_6)
        self.btnLimparClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnLimparClientes.setObjectName("btnLimparClientes")
        self.horizontalLayout_5.addWidget(self.btnLimparClientes)
        self.btnEditarClientes = QtWidgets.QPushButton(self.frame_6)
        self.btnEditarClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnEditarClientes.setObjectName("btnEditarClientes")
        self.horizontalLayout_5.addWidget(self.btnEditarClientes)
        self.btnPesquisarClientes = QtWidgets.QPushButton(self.tab_10)
        self.btnPesquisarClientes.setGeometry(QtCore.QRect(940, 600, 161, 51))
        self.btnPesquisarClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnPesquisarClientes.setObjectName("btnPesquisarClientes")
        self.inputPesquisaClientes = QtWidgets.QLineEdit(self.tab_10)
        self.inputPesquisaClientes.setGeometry(QtCore.QRect(200, 600, 691, 51))
        self.inputPesquisaClientes.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"\n"
"    background-color: #fff;\n"
"")
        self.inputPesquisaClientes.setObjectName("inputPesquisaClientes")
        self.btnTodosClientes = QtWidgets.QPushButton(self.tab_10)
        self.btnTodosClientes.setGeometry(QtCore.QRect(1120, 600, 161, 51))
        self.btnTodosClientes.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnTodosClientes.setObjectName("btnTodosClientes")
        self.tabWidget.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.inputPesquisaServicos = QtWidgets.QLineEdit(self.tab_11)
        self.inputPesquisaServicos.setGeometry(QtCore.QRect(200, 600, 691, 51))
        self.inputPesquisaServicos.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"    background-color: #fff;\n"
"")
        self.inputPesquisaServicos.setObjectName("inputPesquisaServicos")
        self.frame_7 = QtWidgets.QFrame(self.tab_11)
        self.frame_7.setGeometry(QtCore.QRect(40, 690, 1211, 66))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnDeleteServicos = QtWidgets.QPushButton(self.frame_7)
        self.btnDeleteServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnDeleteServicos.setObjectName("btnDeleteServicos")
        self.horizontalLayout_6.addWidget(self.btnDeleteServicos)
        self.btnGerarExelServicos = QtWidgets.QPushButton(self.frame_7)
        self.btnGerarExelServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnGerarExelServicos.setObjectName("btnGerarExelServicos")
        self.horizontalLayout_6.addWidget(self.btnGerarExelServicos)
        self.btnInserirServicos = QtWidgets.QPushButton(self.frame_7)
        self.btnInserirServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnInserirServicos.setObjectName("btnInserirServicos")
        self.horizontalLayout_6.addWidget(self.btnInserirServicos)
        self.btnLimparServicos = QtWidgets.QPushButton(self.frame_7)
        self.btnLimparServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnLimparServicos.setObjectName("btnLimparServicos")
        self.horizontalLayout_6.addWidget(self.btnLimparServicos)
        self.btnEditarServicos = QtWidgets.QPushButton(self.frame_7)
        self.btnEditarServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnEditarServicos.setObjectName("btnEditarServicos")
        self.horizontalLayout_6.addWidget(self.btnEditarServicos)
        self.btnPesquisarServicos = QtWidgets.QPushButton(self.tab_11)
        self.btnPesquisarServicos.setGeometry(QtCore.QRect(940, 600, 161, 51))
        self.btnPesquisarServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnPesquisarServicos.setObjectName("btnPesquisarServicos")
        self.tabelaServicos = QtWidgets.QTableWidget(self.tab_11)
        self.tabelaServicos.setGeometry(QtCore.QRect(10, 20, 1331, 521))
        self.tabelaServicos.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabelaServicos.setStyleSheet("QTableView {\n"
"    background-color: #3498db;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}")
        self.tabelaServicos.setShowGrid(True)
        self.tabelaServicos.setWordWrap(True)
        self.tabelaServicos.setObjectName("tabelaServicos")
        self.tabelaServicos.setColumnCount(9)
        self.tabelaServicos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tabelaServicos.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaServicos.setHorizontalHeaderItem(8, item)
        self.tabelaServicos.horizontalHeader().setDefaultSectionSize(150)
        self.tabelaServicos.horizontalHeader().setSortIndicatorShown(False)
        self.tabelaServicos.horizontalHeader().setStretchLastSection(True)
        self.tabelaServicos.verticalHeader().setCascadingSectionResizes(False)
        self.tabelaServicos.verticalHeader().setHighlightSections(False)
        self.tabelaServicos.verticalHeader().setSortIndicatorShown(False)
        self.tabelaServicos.verticalHeader().setStretchLastSection(False)
        self.btnTodosServicos = QtWidgets.QPushButton(self.tab_11)
        self.btnTodosServicos.setGeometry(QtCore.QRect(1120, 600, 161, 51))
        self.btnTodosServicos.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnTodosServicos.setObjectName("btnTodosServicos")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.btnTodosDespesa = QtWidgets.QPushButton(self.tab_12)
        self.btnTodosDespesa.setGeometry(QtCore.QRect(1120, 600, 161, 51))
        self.btnTodosDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnTodosDespesa.setObjectName("btnTodosDespesa")
        self.btnPesquisarDespesa = QtWidgets.QPushButton(self.tab_12)
        self.btnPesquisarDespesa.setGeometry(QtCore.QRect(940, 600, 161, 51))
        self.btnPesquisarDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnPesquisarDespesa.setObjectName("btnPesquisarDespesa")
        self.inputPesquisaDespesa = QtWidgets.QLineEdit(self.tab_12)
        self.inputPesquisaDespesa.setGeometry(QtCore.QRect(200, 600, 691, 51))
        self.inputPesquisaDespesa.setStyleSheet("border-radius: 15px;\n"
"border-style: outset;\n"
"border-width:2px;\n"
"background-color: rgb(170, 255, 255);\n"
"\n"
"    background-color: #fff;")
        self.inputPesquisaDespesa.setObjectName("inputPesquisaDespesa")
        self.frame_10 = QtWidgets.QFrame(self.tab_12)
        self.frame_10.setGeometry(QtCore.QRect(40, 690, 1211, 66))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnDeleteDespesa = QtWidgets.QPushButton(self.frame_10)
        self.btnDeleteDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnDeleteDespesa.setObjectName("btnDeleteDespesa")
        self.horizontalLayout_9.addWidget(self.btnDeleteDespesa)
        self.btnGerarExelDespesa = QtWidgets.QPushButton(self.frame_10)
        self.btnGerarExelDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnGerarExelDespesa.setObjectName("btnGerarExelDespesa")
        self.horizontalLayout_9.addWidget(self.btnGerarExelDespesa)
        self.btnInserirDespesa = QtWidgets.QPushButton(self.frame_10)
        self.btnInserirDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnInserirDespesa.setObjectName("btnInserirDespesa")
        self.horizontalLayout_9.addWidget(self.btnInserirDespesa)
        self.btnLimparDespesa = QtWidgets.QPushButton(self.frame_10)
        self.btnLimparDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnLimparDespesa.setObjectName("btnLimparDespesa")
        self.horizontalLayout_9.addWidget(self.btnLimparDespesa)
        self.btnEditarDespesa = QtWidgets.QPushButton(self.frame_10)
        self.btnEditarDespesa.setStyleSheet("QPushButton {\n"
"    background-color: #3498db;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    font-size: 18px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    display: inline-block;\n"
"    margin: 4px 2px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3cb0fd;\n"
"}")
        self.btnEditarDespesa.setObjectName("btnEditarDespesa")
        self.horizontalLayout_9.addWidget(self.btnEditarDespesa)
        self.tabelaDespesa = QtWidgets.QTableWidget(self.tab_12)
        self.tabelaDespesa.setGeometry(QtCore.QRect(10, 20, 1321, 521))
        self.tabelaDespesa.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tabelaDespesa.setStyleSheet("QTableView {\n"
"    background-color: #3498db;\n"
"}\n"
"\n"
"QTableView::item {\n"
"    background-color: #3498db;\n"
"    color: white;\n"
"}")
        self.tabelaDespesa.setShowGrid(True)
        self.tabelaDespesa.setWordWrap(True)
        self.tabelaDespesa.setObjectName("tabelaDespesa")
        self.tabelaDespesa.setColumnCount(7)
        self.tabelaDespesa.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaDespesa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaDespesa.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaDespesa.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaDespesa.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        self.tabelaDespesa.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaDespesa.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabelaDespesa.setHorizontalHeaderItem(6, item)
        self.tabelaDespesa.horizontalHeader().setDefaultSectionSize(150)
        self.tabelaDespesa.horizontalHeader().setSortIndicatorShown(False)
        self.tabelaDespesa.horizontalHeader().setStretchLastSection(True)
        self.tabelaDespesa.verticalHeader().setCascadingSectionResizes(False)
        self.tabelaDespesa.verticalHeader().setHighlightSections(False)
        self.tabelaDespesa.verticalHeader().setSortIndicatorShown(False)
        self.tabelaDespesa.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tab_12, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1351, 761))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(170, 90, 431, 461))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(0, 0, 431, 61))
        self.label.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(0, 70, 191, 61))
        self.label_3.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(240, 70, 191, 61))
        self.label_4.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(0, 160, 191, 61))
        self.label_5.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(0, 250, 191, 61))
        self.label_7.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_7.setObjectName("label_7")
        self.entrada_bruta = QtWidgets.QLabel(self.frame_3)
        self.entrada_bruta.setGeometry(QtCore.QRect(0, 330, 431, 61))
        self.entrada_bruta.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.entrada_bruta.setObjectName("entrada_bruta")
        self.qt_servicos = QtWidgets.QLabel(self.frame_3)
        self.qt_servicos.setGeometry(QtCore.QRect(240, 160, 191, 61))
        self.qt_servicos.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.qt_servicos.setText("")
        self.qt_servicos.setObjectName("qt_servicos")
        self.val_lucro = QtWidgets.QLabel(self.frame_3)
        self.val_lucro.setGeometry(QtCore.QRect(240, 250, 191, 61))
        self.val_lucro.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.val_lucro.setText("")
        self.val_lucro.setObjectName("val_lucro")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(160, 600, 1001, 81))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(490, 20, 171, 41))
        self.lineEdit_10.setStyleSheet("\n"
"border-color:black;")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.fat_total = QtWidgets.QLabel(self.frame_5)
        self.fat_total.setGeometry(QtCore.QRect(240, 10, 431, 61))
        self.fat_total.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.fat_total.setText("")
        self.fat_total.setObjectName("fat_total")
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setGeometry(QtCore.QRect(730, 90, 431, 461))
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_13 = QtWidgets.QLabel(self.frame_8)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 431, 61))
        self.label_13.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_8)
        self.label_14.setGeometry(QtCore.QRect(0, 70, 191, 61))
        self.label_14.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_8)
        self.label_15.setGeometry(QtCore.QRect(240, 70, 191, 61))
        self.label_15.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_8)
        self.label_16.setGeometry(QtCore.QRect(0, 160, 191, 61))
        self.label_16.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_8)
        self.label_17.setGeometry(QtCore.QRect(0, 250, 191, 61))
        self.label_17.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.label_17.setObjectName("label_17")
        self.saida_bruta = QtWidgets.QLabel(self.frame_8)
        self.saida_bruta.setGeometry(QtCore.QRect(0, 330, 431, 61))
        self.saida_bruta.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.saida_bruta.setObjectName("saida_bruta")
        self.variaveis = QtWidgets.QLabel(self.frame_8)
        self.variaveis.setGeometry(QtCore.QRect(240, 250, 191, 61))
        self.variaveis.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.variaveis.setText("")
        self.variaveis.setObjectName("variaveis")
        self.fixo = QtWidgets.QLabel(self.frame_8)
        self.fixo.setGeometry(QtCore.QRect(240, 160, 191, 61))
        self.fixo.setStyleSheet("\n"
"border-width:2px;\n"
"border-style:outset;\n"
"border-color:black;")
        self.fixo.setText("")
        self.fixo.setObjectName("fixo")
        self.tabWidget.addTab(self.tab, "")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(869, 0, 391, 81))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.hora = QtWidgets.QLabel(self.frame_9)
        self.hora.setGeometry(QtCore.QRect(10, 50, 201, 41))
        self.hora.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
"")
        self.hora.setObjectName("hora")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">dssdf</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#ffffff;\">PYTSHOP</span></p><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">Sistema de gerenciamento</span></p><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">PETSHOP</span></p><p align=\"center\"><br/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_13), _translate("MainWindow", "Inicio"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "nome"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "data"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "hora"))
        self.label_18.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">dssdf</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#ffffff;\">PYTSHOP</span></p><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">Sistema de gerenciamento</span></p><p align=\"center\"><span style=\" font-size:24pt; color:#ffffff;\">PETSHOP</span></p><p align=\"center\"><br/></p></body></html>"))
        self.btnPesquisar_2.setText(_translate("MainWindow", "concluido"))
        self.btnAtualizar_3.setText(_translate("MainWindow", "Atualizar"))
        self.label_6.setText(_translate("MainWindow", "Grafico de vendas(Mensal) em R$"))
        self.label_2.setText(_translate("MainWindow", "O grafico será atualido quando o programa reiniciar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Menu"))
        item = self.tabelaClientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tabelaClientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "nome"))
        item = self.tabelaClientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "tipodopet"))
        item = self.tabelaClientes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "wats"))
        item = self.tabelaClientes.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "nome"))
        item = self.tabelaClientes.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "cpf"))
        item = self.tabelaClientes.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "UF"))
        item = self.tabelaClientes.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "endereco"))
        item = self.tabelaClientes.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "numero"))
        item = self.tabelaClientes.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "sobrenome"))
        self.btnDeleteClientes.setText(_translate("MainWindow", "Deletar"))
        self.btnGerarExelClientes.setText(_translate("MainWindow", "Gerar Exel"))
        self.btnInserirClientes.setText(_translate("MainWindow", "Inserir"))
        self.btnLimparClientes.setText(_translate("MainWindow", "Limpar"))
        self.btnEditarClientes.setText(_translate("MainWindow", "Editar"))
        self.btnPesquisarClientes.setText(_translate("MainWindow", "Pesquisar"))
        self.btnTodosClientes.setText(_translate("MainWindow", "Todos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), _translate("MainWindow", "Clientes"))
        self.btnDeleteServicos.setText(_translate("MainWindow", "Deletar"))
        self.btnGerarExelServicos.setText(_translate("MainWindow", "Gerar Exel"))
        self.btnInserirServicos.setText(_translate("MainWindow", "Inserir"))
        self.btnLimparServicos.setText(_translate("MainWindow", "Limpar"))
        self.btnEditarServicos.setText(_translate("MainWindow", "Editar"))
        self.btnPesquisarServicos.setText(_translate("MainWindow", "Pesquisar"))
        self.tabelaServicos.setSortingEnabled(False)
        item = self.tabelaServicos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tabelaServicos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Id_cliente"))
        item = self.tabelaServicos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Servico"))
        item = self.tabelaServicos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Pagamento"))
        item = self.tabelaServicos.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total"))
        item = self.tabelaServicos.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "agendado"))
        item = self.tabelaServicos.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Data agnd"))
        item = self.tabelaServicos.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "hora"))
        item = self.tabelaServicos.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "descricao"))
        self.btnTodosServicos.setText(_translate("MainWindow", "Todos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Servicos"))
        self.btnTodosDespesa.setText(_translate("MainWindow", "Todos"))
        self.btnPesquisarDespesa.setText(_translate("MainWindow", "Pesquisar"))
        self.btnDeleteDespesa.setText(_translate("MainWindow", "Deletar"))
        self.btnGerarExelDespesa.setText(_translate("MainWindow", "Gerar Exel"))
        self.btnInserirDespesa.setText(_translate("MainWindow", "Inserir"))
        self.btnLimparDespesa.setText(_translate("MainWindow", "Limpar"))
        self.btnEditarDespesa.setText(_translate("MainWindow", "Editar"))
        self.tabelaDespesa.setSortingEnabled(False)
        item = self.tabelaDespesa.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tabelaDespesa.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "despesas"))
        item = self.tabelaDespesa.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "tipo"))
        item = self.tabelaDespesa.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "agendado"))
        item = self.tabelaDespesa.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "valor"))
        item = self.tabelaDespesa.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "status"))
        item = self.tabelaDespesa.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Data "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "Despesas"))
        self.label.setText(_translate("MainWindow", "Faturamento"))
        self.label_3.setText(_translate("MainWindow", "Tipo"))
        self.label_4.setText(_translate("MainWindow", "Valor"))
        self.label_5.setText(_translate("MainWindow", "Qnt.Servicos:"))
        self.label_7.setText(_translate("MainWindow", "Valor lucro:"))
        self.entrada_bruta.setText(_translate("MainWindow", "Faturamento bruto"))
        self.label_13.setText(_translate("MainWindow", "Saidas"))
        self.label_14.setText(_translate("MainWindow", "Tipo"))
        self.label_15.setText(_translate("MainWindow", "Valor"))
        self.label_16.setText(_translate("MainWindow", "Fixos:"))
        self.label_17.setText(_translate("MainWindow", "Variaveis"))
        self.saida_bruta.setText(_translate("MainWindow", "Somatoria bruta:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Fechamento mensal"))
        self.hora.setText(_translate("MainWindow", "00:00:00"))
